[project]
name = "python-application-template"
version = "0.1.0"
description = "A cookiecutter template for python applications"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cookiecutter>=2.6.0",
    "pytest>=8.3.4",
]
